<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CTP.Application\CTP.Application.csproj" />
    <ProjectReference Include="..\CTP.Domain\CTP.Domain.csproj" />
    <ProjectReference Include="..\CTP.Infrastructure\CTP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".temp-migrator\" />
    <Folder Include=".temp\" />
    <Folder Include="Models\NewFolder\" />
  </ItemGroup>

</Project>
