// <auto-generated />
using System;
using CTP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910050736_InitialSqlServerDb")]
    partial class InitialSqlServerDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CTP.Domain.Entities.Committee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("CTP.Domain.Entities.EntityInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizationEntityId")
                        .HasColumnType("int");

                    b.Property<int>("PreparerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationEntityId");

                    b.HasIndex("PreparerId");

                    b.ToTable("EntityInputs");
                });

            modelBuilder.Entity("CTP.Domain.Entities.MonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityCompletionRate")
                        .HasColumnType("int");

                    b.Property<int>("AdkarAbility")
                        .HasColumnType("int");

                    b.Property<int>("AdkarAwareness")
                        .HasColumnType("int");

                    b.Property<int>("AdkarDesire")
                        .HasColumnType("int");

                    b.Property<int>("AdkarKnowledge")
                        .HasColumnType("int");

                    b.Property<int>("AdkarReinforcement")
                        .HasColumnType("int");

                    b.Property<string>("AdoptionBarriers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdoptionScore")
                        .HasColumnType("int");

                    b.Property<string>("AffectedGroups")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommitteeRecommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EvidenceLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutedActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpactScope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImprovementOpportunities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitialRecommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MostInNeedGroup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Obstacles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationEntityId")
                        .HasColumnType("int");

                    b.Property<int>("PreparerId")
                        .HasColumnType("int");

                    b.Property<int>("ReadinessScore")
                        .HasColumnType("int");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequiredSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Risks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuccessStories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatWillChange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatWillNotChange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyImportant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationEntityId");

                    b.HasIndex("PreparerId");

                    b.ToTable("MonthlyReports");
                });

            modelBuilder.Entity("CTP.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TextColorClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CTP.Domain.Entities.OrganizationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OrganizationEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityCode = "UNIT-01",
                            EntityName = "وحدة التحول الرقمي",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("CTP.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionOwner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ChairReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExpectedImpact")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GapType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IncludeInExecutiveSummary")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeInImpactDashboard")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeInInstitutionalReport")
                        .HasColumnType("bit");

                    b.Property<int>("MonthlyReportId")
                        .HasColumnType("int");

                    b.Property<string>("RecommendationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SuccessIndicator")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyReportId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("CTP.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "STAFF",
                            RoleName = "المنسوبون"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "MANAGER",
                            RoleName = "القادة والمدراء المباشرون"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "AMBASSADOR",
                            RoleName = "سفراء التغيير"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "UNIT_LEADER",
                            RoleName = "أصحاب السعادة قادة الوحدات والمدراء"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "COMMITTEE_MEMBER",
                            RoleName = "أعضاء لجنة شركاء التغيير"
                        },
                        new
                        {
                            RoleId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "COMMITTEE_CHAIR",
                            RoleName = "رئيس لجنة شركاء التغيير"
                        },
                        new
                        {
                            RoleId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "CHIEF_OF_STAFF",
                            RoleName = "سعادة رئيس فريق عمل القائد"
                        },
                        new
                        {
                            RoleId = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "DEPUTY_LEADER",
                            RoleName = "سعادة نائب القائد"
                        },
                        new
                        {
                            RoleId = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "LEADER",
                            RoleName = "معالي القائد"
                        },
                        new
                        {
                            RoleId = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleCode = "CORP_COMMS",
                            RoleName = "الاتصال المؤسسي"
                        });
                });

            modelBuilder.Entity("CTP.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<int?>("OrganizationEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PasswordExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("OrganizationEntityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "مستخدم منسوب",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "staff"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "مدير مباشر",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "manager"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "سفير التغيير",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "ambassador"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "قائد الوحدة",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "unitleader"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "عضو اللجنة",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "member"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "رئيس اللجنة",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "chair"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "رئيس فريق عمل القائد",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "chief"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "نائب القائد",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "deputy"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "معالي القائد",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "leader"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            FullName = "موظف الاتصال",
                            IsActive = true,
                            MustChangePassword = false,
                            OrganizationEntityId = 1,
                            PasswordHash = "123456",
                            Username = "comms"
                        });
                });

            modelBuilder.Entity("CTP.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 5
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 6,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 6
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 7,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 7
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 8,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 8
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 9,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 9
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 10,
                            AssignedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserRoleId = 10
                        });
                });

            modelBuilder.Entity("CTP.Domain.Entities.EntityInput", b =>
                {
                    b.HasOne("CTP.Domain.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTP.Domain.Entities.User", "Preparer")
                        .WithMany()
                        .HasForeignKey("PreparerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Preparer");
                });

            modelBuilder.Entity("CTP.Domain.Entities.MonthlyReport", b =>
                {
                    b.HasOne("CTP.Domain.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CTP.Domain.Entities.User", "Preparer")
                        .WithMany()
                        .HasForeignKey("PreparerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Preparer");
                });

            modelBuilder.Entity("CTP.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CTP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CTP.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("CTP.Domain.Entities.MonthlyReport", "SourceReport")
                        .WithMany()
                        .HasForeignKey("MonthlyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceReport");
                });

            modelBuilder.Entity("CTP.Domain.Entities.User", b =>
                {
                    b.HasOne("CTP.Domain.Entities.OrganizationEntity", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationEntityId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CTP.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("CTP.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTP.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CTP.Domain.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CTP.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CTP.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
